export const birthCountries = [
  'Côte d’Ivoire',
  'Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre', 'Angola',
  'Antigua-et-Barbuda', 'Arabie saoudite', 'Argentine', 'Arménie', 'Australie', 'Autriche',
  'Azerbaïdjan', 'Bahamas', 'Bahreïn', 'Bangladesh', 'Barbade', 'Belgique', 'Belize', 'Bénin',
  'Bhoutan', 'Biélorussie', 'Birmanie', 'Bolivie', 'Bosnie-Herzégovine', 'Botswana', 'Brésil',
  'Brunei', 'Bulgarie', 'Burkina Faso', 'Burundi', 'Cambodge', 'Cameroun', 'Canada', 'Cap-Vert',
  'République centrafricaine', 'Chili', 'Chine', 'Chypre', 'Colombie', 'Comores', 'Congo',
  'République démocratique du Congo', 'Corée du Nord', 'Corée du Sud', 'Costa Rica', 'Croatie',
  'Cuba', 'Danemark', 'Djibouti', 'Dominique', 'République dominicaine', 'Saint-Vincent-et-les-Grenadines',
  'Égypte', 'Émirats arabes unis', 'Équateur', 'Érythrée', 'Espagne', 'Estonie', 'Eswatini',
  'États-Unis', 'Éthiopie', 'Fidji', 'Finlande', 'France', 'Haïti', 'Honduras', 'Hongrie',
  'Gabon', 'Gambie', 'Géorgie', 'Ghana', 'Grèce', 'Grenade', 'Guatemala', 'Guinée', 'Guinée-Bissau',
  'Guinée équatoriale', 'Guyana', 'Inde', 'Indonésie', 'Irak', 'Iran', 'Irlande', 'Islande', 'Italie',
  'Jamaïque', 'Japon', 'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizistan', 'Kiribati', 'Koweït',
  'Laos', 'Lesotho', 'Lettonie', 'Liban', 'Libéria', 'Libye', 'Liechtenstein', 'Lituanie', 'Luxembourg',
  'Macédoine du Nord', 'Madagascar', 'Malaisie', 'Monténégro', 'Mozambique', 'Saint-Marin',
  'Namibie', 'Nauru', 'Népal', 'Nicaragua', 'Niger', 'Nigéria', 'Norvège', 'Nouvelle-Zélande',
  'Oman', 'Ouganda', 'Ouzbékistan', 'Israël', 'Mali', 'Malte', 'Maroc', 'Îles Marshall', 'Maurice',
  'Pakistan', 'Palaos', 'Palestine', 'Panama', 'Papouasie-Nouvelle-Guinée', 'Philippines', 'Pologne', 'Portugal',
  'Qatar', 'Roumanie', 'Royaume-Uni', 'Russie', 'Rwanda', 'Mauritanie', 'Mexique', 'Malawi', 'Maldives',
  'Saint-Kitts-et-Nevis', 'Sainte-Lucie', 'Salvador', 'Samoa', 'Sao Tomé-et-Principe', 'Sénégal', 'Serbie', 'Seychelles', 'Sierra Leone', 'Singapour', 'Slovaquie', 'Slovénie', 'Somalie', 'Soudan', 'Soudan du Sud', 'Sri Lanka', 'Suède', 'Suisse', 'Suriname', 'Syrie',
  'Tadjikistan', 'Tanzanie', 'Tchad', 'République tchèque', 'Thaïlande', 'Tonga', 'Trinité-et-Trinidade', 'Tunisie', 'Turkménistan', 'Turquie', 'Tuvalu',
  'Ukraine', 'Uruguay', 'Vanuatu', 'Vatican', 'Venezuela', 'Viêt Nam', 'Micronésie', 'Moldavie', 'Monaco', 'Mongolie',
  'Yémen', 'Zambie', 'Zimbabwe', 'Autre', 'Paraguay', 'Pays-Bas', 'Pérou', 'Timor oriental', 'Togo',
];